import { NextResponse } from "next/server";
import connectToDB from "@/lib/db/connect";
import Achievement from "@/lib/models/Achievement";

const achievements = [
  // ===== Exchange Master (Mistrz Wymian) =====
  {
    id: "exchange_master_bronze",
    seriesId: "exchange_master",
    seriesNameKey: "achievements.series.trading",
    nameKey: "achievements.exchange_master_bronze.name",
    descriptionKey: "achievements.exchange_master_bronze.description",
    icon: "✨",
    tier: "bronze",
    category: "trading",
    points: 10,
    requirement: { completedTransactions: 1 },
  },
  {
    id: "exchange_master_silver",
    seriesId: "exchange_master",
    seriesNameKey: "achievements.series.trading",
    nameKey: "achievements.exchange_master_silver.name",
    descriptionKey: "achievements.exchange_master_silver.description",
    icon: "📢",
    tier: "silver",
    category: "trading",
    points: 25,
    requirement: { completedTransactions: 5 },
  },
  {
    id: "exchange_master_gold",
    seriesId: "exchange_master",
    seriesNameKey: "achievements.series.trading",
    nameKey: "achievements.exchange_master_gold.name",
    descriptionKey: "achievements.exchange_master_gold.description",
    icon: "⚖️",
    tier: "gold",
    category: "trading",
    points: 50,
    requirement: { completedTransactions: 25 },
  },
  {
    id: "exchange_master_platinum",
    seriesId: "exchange_master",
    seriesNameKey: "achievements.series.trading",
    nameKey: "achievements.exchange_master_platinum.name",
    descriptionKey: "achievements.exchange_master_platinum.description",
    icon: "🌄",
    tier: "platinum",
    category: "trading",
    points: 100,
    requirement: { completedTransactions: 100 },
  },

  // ===== Trusted Trader (Zaufany Handlarz) =====
  {
    id: "trusted_trader_bronze",
    seriesId: "trusted_trader",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.trusted_trader_bronze.name",
    descriptionKey: "achievements.trusted_trader_bronze.description",
    icon: "🫂",
    tier: "bronze",
    category: "reputation",
    points: 10,
    requirement: { positiveReviews: 5 },
  },
  {
    id: "trusted_trader_silver",
    seriesId: "trusted_trader",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.trusted_trader_silver.name",
    descriptionKey: "achievements.trusted_trader_silver.description",
    icon: "👀",
    tier: "silver",
    category: "reputation",
    points: 25,
    requirement: { positiveReviews: 25 },
  },
  {
    id: "trusted_trader_gold",
    seriesId: "trusted_trader",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.trusted_trader_gold.name",
    descriptionKey: "achievements.trusted_trader_gold.description",
    icon: "🎬",
    tier: "gold",
    category: "reputation",
    points: 50,
    requirement: { positiveReviews: 50 },
  },
  {
    id: "trusted_trader_platinum",
    seriesId: "trusted_trader",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.trusted_trader_platinum.name",
    descriptionKey: "achievements.trusted_trader_platinum.description",
    icon: "🎸",
    tier: "platinum",
    category: "reputation",
    points: 100,
    requirement: { positiveReviews: 100 },
  },

  // ===== Perfect Rating (Perfekcyjna Ocena) =====
  {
    id: "perfect_rating_bronze",
    seriesId: "perfect_rating",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.perfect_rating_bronze.name",
    descriptionKey: "achievements.perfect_rating_bronze.description",
    icon: "📺",
    tier: "bronze",
    category: "reputation",
    points: 15,
    requirement: { averageRating: 5.0, minReviews: 5 },
  },
  {
    id: "perfect_rating_silver",
    seriesId: "perfect_rating",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.perfect_rating_silver.name",
    descriptionKey: "achievements.perfect_rating_silver.description",
    icon: "🎯",
    tier: "silver",
    category: "reputation",
    points: 30,
    requirement: { averageRating: 5.0, minReviews: 15 },
  },
  {
    id: "perfect_rating_gold",
    seriesId: "perfect_rating",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.perfect_rating_gold.name",
    descriptionKey: "achievements.perfect_rating_gold.description",
    icon: "⭐",
    tier: "gold",
    category: "reputation",
    points: 60,
    requirement: { averageRating: 5.0, minReviews: 50 },
  },
  {
    id: "perfect_rating_platinum",
    seriesId: "perfect_rating",
    seriesNameKey: "achievements.series.reputation",
    nameKey: "achievements.perfect_rating_platinum.name",
    descriptionKey: "achievements.perfect_rating_platinum.description",
    icon: "🏔️",
    tier: "platinum",
    category: "reputation",
    points: 120,
    requirement: { averageRating: 5.0, minReviews: 100 },
  },

  // ===== Book Collector (Kolekcjoner Książek) =====
  {
    id: "book_collector_bronze",
    seriesId: "book_collector",
    seriesNameKey: "achievements.series.collection",
    nameKey: "achievements.book_collector_bronze.name",
    descriptionKey: "achievements.book_collector_bronze.description",
    icon: "🎭",
    tier: "bronze",
    category: "collection",
    points: 5,
    requirement: { totalBooksAdded: 5 },
  },
  {
    id: "book_collector_silver",
    seriesId: "book_collector",
    seriesNameKey: "achievements.series.collection",
    nameKey: "achievements.book_collector_silver.name",
    descriptionKey: "achievements.book_collector_silver.description",
    icon: "🗡️",
    tier: "silver",
    category: "collection",
    points: 20,
    requirement: { totalBooksAdded: 25 },
  },
  {
    id: "book_collector_gold",
    seriesId: "book_collector",
    seriesNameKey: "achievements.series.collection",
    nameKey: "achievements.book_collector_gold.name",
    descriptionKey: "achievements.book_collector_gold.description",
    icon: "📜",
    tier: "gold",
    category: "collection",
    points: 40,
    requirement: { totalBooksAdded: 100 },
  },
  {
    id: "book_collector_platinum",
    seriesId: "book_collector",
    seriesNameKey: "achievements.series.collection",
    nameKey: "achievements.book_collector_platinum.name",
    descriptionKey: "achievements.book_collector_platinum.description",
    icon: "🔮",
    tier: "platinum",
    category: "collection",
    points: 80,
    requirement: { totalBooksAdded: 250 },
  },

  // ===== Social Butterfly (Towarzyski Motyl) =====
  {
    id: "social_butterfly_bronze",
    seriesId: "social_butterfly",
    seriesNameKey: "achievements.series.social",
    nameKey: "achievements.social_butterfly_bronze.name",
    descriptionKey: "achievements.social_butterfly_bronze.description",
    icon: "👋",
    tier: "bronze",
    category: "community",
    points: 5,
    requirement: { conversationsStarted: 5 },
  },
  {
    id: "social_butterfly_silver",
    seriesId: "social_butterfly",
    seriesNameKey: "achievements.series.social",
    nameKey: "achievements.social_butterfly_silver.name",
    descriptionKey: "achievements.social_butterfly_silver.description",
    icon: "🌉",
    tier: "silver",
    category: "community",
    points: 20,
    requirement: { conversationsStarted: 25 },
  },
  {
    id: "social_butterfly_gold",
    seriesId: "social_butterfly",
    seriesNameKey: "achievements.series.social",
    nameKey: "achievements.social_butterfly_gold.name",
    descriptionKey: "achievements.social_butterfly_gold.description",
    icon: "🐺",
    tier: "gold",
    category: "community",
    points: 40,
    requirement: { conversationsStarted: 100 },
  },
  {
    id: "social_butterfly_platinum",
    seriesId: "social_butterfly",
    seriesNameKey: "achievements.series.social",
    nameKey: "achievements.social_butterfly_platinum.name",
    descriptionKey: "achievements.social_butterfly_platinum.description",
    icon: "🍷",
    tier: "platinum",
    category: "community",
    points: 80,
    requirement: { conversationsStarted: 250 },
  },

  // ===== Generous Giver (Hojny Dawca) =====
  {
    id: "generous_giver_bronze",
    seriesId: "generous_giver",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.generous_giver_bronze.name",
    descriptionKey: "achievements.generous_giver_bronze.description",
    icon: "🤏",
    tier: "bronze",
    category: "community",
    points: 10,
    requirement: { freeGiveaways: 1 },
  },
  {
    id: "generous_giver_silver",
    seriesId: "generous_giver",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.generous_giver_silver.name",
    descriptionKey: "achievements.generous_giver_silver.description",
    icon: "⏳",
    tier: "silver",
    category: "community",
    points: 30,
    requirement: { freeGiveaways: 5 },
  },
  {
    id: "generous_giver_gold",
    seriesId: "generous_giver",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.generous_giver_gold.name",
    descriptionKey: "achievements.generous_giver_gold.description",
    icon: "🕊️",
    tier: "gold",
    category: "community",
    points: 60,
    requirement: { freeGiveaways: 20 },
  },
  {
    id: "generous_giver_platinum",
    seriesId: "generous_giver",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.generous_giver_platinum.name",
    descriptionKey: "achievements.generous_giver_platinum.description",
    icon: "🥇",
    tier: "platinum",
    category: "community",
    points: 120,
    requirement: { freeGiveaways: 50 },
  },

  // ===== Thoughtful Reviewer (Wnikliwy Recenzent) =====
  {
    id: "thoughtful_reviewer_bronze",
    seriesId: "thoughtful_reviewer",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.thoughtful_reviewer_bronze.name",
    descriptionKey: "achievements.thoughtful_reviewer_bronze.description",
    icon: "💼",
    tier: "bronze",
    category: "community",
    points: 5,
    requirement: { detailedReviews: 5 },
  },
  {
    id: "thoughtful_reviewer_silver",
    seriesId: "thoughtful_reviewer",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.thoughtful_reviewer_silver.name",
    descriptionKey: "achievements.thoughtful_reviewer_silver.description",
    icon: "💵",
    tier: "silver",
    category: "community",
    points: 20,
    requirement: { detailedReviews: 25 },
  },
  {
    id: "thoughtful_reviewer_gold",
    seriesId: "thoughtful_reviewer",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.thoughtful_reviewer_gold.name",
    descriptionKey: "achievements.thoughtful_reviewer_gold.description",
    icon: "👨‍⚖️",
    tier: "gold",
    category: "community",
    points: 40,
    requirement: { detailedReviews: 100 },
  },
  {
    id: "thoughtful_reviewer_platinum",
    seriesId: "thoughtful_reviewer",
    seriesNameKey: "achievements.series.community",
    nameKey: "achievements.thoughtful_reviewer_platinum.name",
    descriptionKey: "achievements.thoughtful_reviewer_platinum.description",
    icon: "🎩",
    tier: "platinum",
    category: "community",
    points: 80,
    requirement: { detailedReviews: 250 },
  },

  // ===== Loyal Member (Lojalny Członek) =====
  {
    id: "loyal_member_bronze",
    seriesId: "loyal_member",
    seriesNameKey: "achievements.series.loyalty",
    nameKey: "achievements.loyal_member_bronze.name",
    descriptionKey: "achievements.loyal_member_bronze.description",
    icon: "🍒",
    tier: "bronze",
    category: "activity",
    points: 10,
    requirement: { loginStreak: 7 },
  },
  {
    id: "loyal_member_silver",
    seriesId: "loyal_member",
    seriesNameKey: "achievements.series.loyalty",
    nameKey: "achievements.loyal_member_silver.name",
    descriptionKey: "achievements.loyal_member_silver.description",
    icon: "⭕",
    tier: "silver",
    category: "activity",
    points: 30,
    requirement: { loginStreak: 30 },
  },
  {
    id: "loyal_member_gold",
    seriesId: "loyal_member",
    seriesNameKey: "achievements.series.loyalty",
    nameKey: "achievements.loyal_member_gold.name",
    descriptionKey: "achievements.loyal_member_gold.description",
    icon: "🌙",
    tier: "gold",
    category: "activity",
    points: 60,
    requirement: { loginStreak: 100 },
  },
  {
    id: "loyal_member_platinum",
    seriesId: "loyal_member",
    seriesNameKey: "achievements.series.loyalty",
    nameKey: "achievements.loyal_member_platinum.name",
    descriptionKey: "achievements.loyal_member_platinum.description",
    icon: "🔪",
    tier: "platinum",
    category: "activity",
    points: 120,
    requirement: { loginStreak: 365 },
  },

  // ===== SPECIAL: Single Achievement (bez serii) =====
  {
    id: "pioneer",
    seriesId: "pioneer",
    seriesNameKey: "achievements.series.special",
    nameKey: "achievements.pioneer.name",
    descriptionKey: "achievements.pioneer.description",
    icon: "🦌",
    tier: "platinum",
    category: "special",
    points: 150,
    requirement: { joinedBefore: "2025-12-01" },
  },

  // ===== SPECIAL: Seasonal =====
  {
    id: "summer_harvest",
    seriesId: "summer_harvest",
    seriesNameKey: "achievements.series.summer",
    nameKey: "achievements.summer_harvest.name",
    descriptionKey: "achievements.summer_harvest.description",
    icon: "🏖️",
    tier: "gold",
    category: "special",
    points: 50,
    requirement: { exchangesInSummer: 10 },
  },
  {
    id: "new_year_contract",
    seriesId: "new_year_contract",
    seriesNameKey: "achievements.series.new_year",
    nameKey: "achievements.new_year_contract.name",
    descriptionKey: "achievements.new_year_contract.description",
    icon: "🥂",
    tier: "gold",
    category: "special",
    points: 50,
    requirement: { exchangeOnNewYear: true },
  },

  // ===== SPECIAL: Milestone =====
  {
    id: "king_of_merchant_guild",
    seriesId: "king_of_merchant_guild",
    seriesNameKey: "achievements.series.special",
    nameKey: "achievements.king_of_merchant_guild.name",
    descriptionKey: "achievements.king_of_merchant_guild.description",
    icon: "👑",
    tier: "platinum",
    category: "special",
    points: 200,
    requirement: { totalPoints: 10000 },
  },
  {
    id: "best_of_the_best",
    seriesId: "best_of_the_best",
    seriesNameKey: "achievements.series.special",
    nameKey: "achievements.best_of_the_best.name",
    descriptionKey: "achievements.best_of_the_best.description",
    icon: "🌟",
    tier: "platinum",
    category: "special",
    points: 300,
    requirement: { rankingPosition: 1, rankingDays: 30 },
  },
];

export async function POST() {
  try {
    await connectToDB();

    await Achievement.deleteMany({});
    await Achievement.insertMany(achievements);

    return NextResponse.json({
      message: "Achievements seeded successfully",
      count: achievements.length,
    });
  } catch (error) {
    console.error("Error seeding achievements:", error);
    return NextResponse.json(
      { error: "Failed to seed achievements" },
      { status: 500 }
    );
  }
}
